/* This file is generated by GenerateTests.java. Please do not modify. */
/*
 * Copyright 2017 - 2020 Volker Berlin (i-net software)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.inetsoftware.jwebassembly.jawa;

import de.inetsoftware.jwebassembly.jawa.jolden.bh.BH;
import de.inetsoftware.jwebassembly.jawa.jolden.bisort.BiSort;
import de.inetsoftware.jwebassembly.jawa.jolden.em3d.Em3d;
import de.inetsoftware.jwebassembly.jawa.jolden.health.Health;
import de.inetsoftware.jwebassembly.jawa.jolden.mst.MST;
import de.inetsoftware.jwebassembly.jawa.jolden.perimeter.Perimeter;
import de.inetsoftware.jwebassembly.jawa.jolden.power.Power;
import de.inetsoftware.jwebassembly.jawa.jolden.treeadd.TreeAdd;
import de.inetsoftware.jwebassembly.jawa.jolden.tsp.TSP;
import de.inetsoftware.jwebassembly.jawa.jolden.voronoi.Voronoi;
import org.junit.Test;

import static de.inetsoftware.jwebassembly.jawa.TestRunner.run;

public class RunJoldenTests {

    @Test
    public void bh() { run( BH.class ); }

    @Test
    public void bisort() { run( BiSort.class ); }

    @Test
    public void em3d() { run( Em3d.class ); }

    @Test
    public void health() { run( Health.class ); }

    @Test
    public void mst() { run( MST.class ); }

    @Test
    public void perimeter() { run( Perimeter.class ); }

    @Test
    public void power() { run( Power.class ); }

    @Test
    public void treeadd() { run( TreeAdd.class ); }

    @Test
    public void tsp() { run( TSP.class ); }

    @Test
    public void voronoi() { run( Voronoi.class ); }

}
